---
__default__:
  partition: 'broadwl'
  time: '01:00:00'
  nodes: '1'
  ntasks: '1'
  cpuspertask: '1'
  output: "output/{rule}.{wildcards}.txt"
  error: "error/{rule}.{wildcards}.txt"
  export: "ALL"
  mem: '25G'
anno2torus_fdr:
  mem: '45G'
run_ldsc:
  mem: '45gb'
  time: '02:00:00'
