
configfile:
    'config.yaml'


#include: "ldsc_snakefile"
include: "gwas_snakefile"

rule all:
    input:
        config['DL_DIR'] +"snp151.txt"
        # expand(config["L2"] +"{pref}.{chrom}.l2.M",pref="atac-seq-reproducible-ctr-ATAC",chrom=19)
