
configfile:
    'config.yaml'


#include: "ldsc_snakefile"
include: "gwas_snakefile"

rule all:
    input:
        config['DL'] +"snp150.h5",
        config['GWAS']+"ptb_gwas.h5"
        # expand(config["L2"] +"{pref}.{chrom}.l2.M",pref="atac-seq-reproducible-ctr-ATAC",chrom=19)
